// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCMWNdJ7o2-4XXLe6fCWWRMlyR3iIBQqU',
    appId: '1:587357455921:android:7c649ed9b6dd5cda107710',
    messagingSenderId: '587357455921',
    projectId: 'chance-bab22',
    databaseURL: 'https://chance-bab22-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chance-bab22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxsvs4Lj8D2Xa7qzBnME7rAAkCM48XUQc',
    appId: '1:587357455921:ios:bb6c7f958f187aa5107710',
    messagingSenderId: '587357455921',
    projectId: 'chance-bab22',
    databaseURL: 'https://chance-bab22-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chance-bab22.appspot.com',
    androidClientId: '587357455921-b2t3r6390999b5ko8a3p98itnf41th1d.apps.googleusercontent.com',
    iosClientId: '587357455921-fdue5dh2afv4b337qdn3jaemosl2th1a.apps.googleusercontent.com',
    iosBundleId: 'com.chanceapp.chanceApp',
  );
}
